### PR TITLE
Added fix for Issue 59: Instructions to search for items

### LINKED ISSUE #59: INSTRUCTIONS: search items
Add inline instructions on how/when to search an item and how the feature is enabled.
An eager user should be helped/guided into enabling and using the search feature. That means linking to the repo README.md on how to enable a local `elasticsearch` instance and explaining how search filters work.

### PR DESCRIPTION
**Pull request by mehulsr**
Fixes #59 
Trying to figure out how to add link to README.md

### CODE REVIEW

**Comment by TimMoore** [comment]
@mehulsr here is a pointer for linking to the README: https://www.playframework.com/documentation/2.5.x/JavaTemplates#Escaping

File: web-gateway/app/views/searchItem.scala.html [hunk 1]
```diff
@@ -12,6 +12,8 @@
 
     <h2>@message("searchItems")</h2>
 
+	<p>@message("searchInstructions")</p>
```
Comment (TimMoore) [inline web-gateway/app/views/searchItem.scala.html]: Please be sure to use spaces rather than tabs for indentation.

If you're using Eclipse, here is a guide for configuring it to use spaces: http://stackoverflow.com/a/408449/29470

Comment (mehulsr) [inline web-gateway/app/views/searchItem.scala.html]: Thanks, will fix this in the next commit. 
I'm not using any IDE at the moment, but the Atom Editor. Is it advisable to use an IDE?

File: web-gateway/conf/messages [hunk 2]
```diff
@@ -85,3 +85,6 @@ invalid.duration=Please enter a valid duration
 invalid.units=Please enter a valid unit
 
 createUserInstructions=Here you can create a new user who can participate in and create auctions.
+searchInstructions=Here you can search for auctioned items. Search functionality can be enabled by downloading and running a local instance of elasticsearch. \
+	Steps for doing this can be found in README.md.\
+	You can filter your search by specifying the maximum price of items to search for and the currency to search in.
```
Comment (ignasi35) [inline web-gateway/conf/messages]: Hi @mehulsr, thanks for this contribution. 
I have a question: are the newlines preserved when rendering this message in HTML? Or put another way, will this message be rendered as 3 `<p>` blocks? If not, is there 

I think we could rewrite them so that the generic instruction on how to use the feature appear first (since they always apply), and the details on how to get the feature up and running (install ES and/or check README) appear last. Also, I think it's worth mentioning that once the system is started, there's no need to restart it when installing and running ES since the search service will be able to recover.

Comment (mehulsr) [inline web-gateway/conf/messages]: Hi @ignasi35 
The newlines are not preserved at the time of rendering in HTML. 
I shall reorder the instructions in the next commit to separate general search instructions and installation instructions.

File: web-gateway/app/views/searchItem.scala.html (hunk 1 above)
Comment (mehulsr) [inline web-gateway/app/views/searchItem.scala.html]: Fixed this is new commit.

File: web-gateway/conf/messages (hunk 2 above)
Comment (mehulsr) [inline web-gateway/conf/messages]: Fixed this is new commit.

**Comment by TimMoore** [comment]
Do you still intend to add a link to `README.md` @mehulsr?

**Comment by mehulsr** [comment]
@TimMoore Yes I think it would be appropriate. I'll try to do it one more time, else we can close the PR?

**Comment by TimMoore** [comment]
OK no worries, just let us know when you're ready for us to merge it.

**Comment by mehulsr** [comment]
Yes, sure :smiley:

**Comment by mehulsr** [comment]
@TimMoore @ignasi35 
It took me a while to figure out, but I added link to the README.md file in search instructions. Currently, this link downloads the README.md file or shows it in the browser (if a Markdown plug in is enabled).
I have also updated the instructions naming convention as suggested in [this PR](https://github.com/lagom/online-auction-java/pull/66). 
Please review and suggest modifications.

File: web-gateway/conf/routes [hunk 3]
```diff
@@ -22,3 +22,5 @@ GET         /search                     controllers.SearchController.searchForm(
 POST        /search                     controllers.SearchController.search()
 
 GET         /assets/*file               controllers.Assets.at(path = "/public", file)
+
+GET         /*file                      controllers.ExternalAssets.at(path="../", file)
```
Comment (ignasi35) [inline web-gateway/conf/routes]: hi @mehulsr we can't do this. With this route I can download any file in the folder including the source code (test http://localhost:9000/LICENSE or http://localhost:9000/build.sbt for example).

I think we can safely link to https://github.com/lagom/online-auction-java/blob/master/README.md  on the instructions (in which case this route won't be necessary).

Comment (mehulsr) [inline web-gateway/conf/routes]: Ah, yes that's true. Okay, pushing with this change now

**Comment by mehulsr** [comment]
@TimMoore @ignasi35 Please review the changes

**Comment by ignasi35** [comment]
Looks great! Thanks @mehulsr
