### PR TITLE
Small fix for bug #30

### LINKED ISSUE #30: It's impossible to create an auction with a currency of Japanese Yen
When you create an auction in Japanese Yen, it's impossible to enter a valid increment, if it's less than 50, you get an error of invalid.step, if it's more than 50, you get an error of invalid.increment.

### PR DESCRIPTION
**Pull request by yg-apaza**
Japanese currency doesn't use decimal places (currency.getDefaultFractionDigits() returns 0). In this case the step should be 1.
Fixes #30

### CODE REVIEW

**Comment by jroper** [comment]
While a step of 1 works - 1 Yen is only 1c, I think we want the step to be 50 Yen, so that you don't have auctions where people are just putting 1 Yen increments in.

The problem I think is in the validation logic, in the ItemForm, which assumes US currency.  The maximum value for the increment should probably be something like 100 times the step, so in US, where the step is 50c, that means $50, while if in Yen, it's 50 Yen, then that would be 5000 Yen as a maximum increment.

**Comment by yg-apaza** [comment]
Oh, I see, can I create another method _isValidIncrement()_ in Currency.java? I think I would need to use currency.getDefaultFractionDigits() to get 10^(2 - n) * step

File: web-gateway/app/controllers/ItemForm.java [hunk 1]
```diff
@@ -29,10 +29,8 @@
 
     public List<ValidationError> validate() {
         List<ValidationError> errors = new ArrayList<>();
-        
+        Currency c = Currency.valueOf(currency);
         try {
-            Currency c = Currency.valueOf(currency);
-
             if (!c.isValidStep(increment.doubleValue())) {
```
Comment (ignasi35) [inline web-gateway/app/controllers/ItemForm.java]: I think the `Currency c = Currency.valueOf(currency);` statement should be inside the `try{} catch{}` block because providing the currency `ASDF` will cause to throw an `IllegalArgumentException`.

That will require your other change (below) to be moved inside this `try{} catch` .

File: web-gateway/app/controllers/Currency.java [hunk 2]
```diff
@@ -77,4 +77,9 @@ public boolean isValidStep(double value) {
         int price = toPriceUnits(value);
         return price % step == 0;
     }
+    
+    public boolean isValidIncrement(double value) {
+    	int price = (int) (value * 2);
+    	return price > 0 && price < 100 * Math.pow(10, 2 - currency.getDefaultFractionDigits());
+    }
```
Comment (jroper) [inline web-gateway/app/controllers/Currency.java]: How about:

```java
int price = toPriceUnits(value);
return price > 0 && price < 100 * step;
```

In US dollars, this makes it 0 < price < $50, and in Yen this makes it 0 < price < 5000.

**Comment by yg-apaza** [comment]
Thanks @jroper , I squashed the commits.

File: web-gateway/app/controllers/ItemForm.java [hunk 3]
```diff
@@ -31,30 +31,21 @@
         List<ValidationError> errors = new ArrayList<>();
         
         try {
-            Currency c = Currency.valueOf(currency);
-
+        	Currency c = Currency.valueOf(currency);
```
Comment (TimMoore) [inline web-gateway/app/controllers/ItemForm.java]: Please make sure you're using only space characters to indent, not tabs. You can probably set up your editor or IDE to do this automatically... let us know what tool you're using if you'd like a pointer on how to set it up.

File: web-gateway/app/controllers/ItemForm.java [hunk 4]
```diff
@@ -31,30 +31,21 @@
...
-
-        // Make sure that the increment and reserve are multiples of 50c - in a real app, this would be more complex
-        // and based on currency specific rules, for now we'll assume currencies that have cents.
-        try {
-            int incrementInt = increment.multiply(BigDecimal.valueOf(2)).intValueExact();
-            if (incrementInt <= 0) {
-                errors.add(new ValidationError("increment", "invalid.increment"));
-            } else if (incrementInt >= 100) {
+            // Make sure that the increment and reserve are multiples of 50c - in a real app, this would be more complex
+            // and based on currency specific rules, for now we'll assume currencies that have cents.
```
Comment (TimMoore) [inline web-gateway/app/controllers/ItemForm.java]: I think this comment is no longer accurate. With this change, it's not assuming cents, and the rule is currency-specific (though still fairly simple). I think the comment can just be deleted.

File: web-gateway/app/controllers/ItemForm.java (hunk 3 above)
Comment (yg-apaza) [inline web-gateway/app/controllers/ItemForm.java]: I'm using Eclipse, how can I configure it?

Comment (TimMoore) [inline web-gateway/app/controllers/ItemForm.java]: @yg-apaza this answer on Stack Overflow covers it well http://stackoverflow.com/a/408449/29470
